name: Build kernel deb packages shell
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Build kernel by shell
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: bash build_action.sh
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
      - name: Archive
        run: tar acvf artifact.tar ${{ github.workspace }}/artifact
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/artifact.tar
          tag_name: latest_release
          name: kernel